# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# YAML reference:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

resources:
  repositories:
    - repository: coretemplate
      type: git
      name: WizPipelines/core-template

trigger:
    batch: 'true'

extends:
  template: main.yml@coretemplate
  parameters:
    technology: 'angular'
    deploymentType: 'storage'
    azResourceName: << Prefixo do nome do recurso de deployment >>
    